### ISSUE TITLE
imprint not reachable !!!!

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/databus-maven-plugin#107]
https://databus.dbpedia.org/imprint

**Comment by holycrab13** [comment]
fixed

**Comment by kurzum** [comment]
Please include a link to the CI test script that will in the future test that this issue is not coming back. 
```
curl -v -L https://databus.dbpedia.org/imprint
```
gives me a curl: (47) Maximum (50) redirects followed

**Comment by holycrab13** [comment]
you can do curl with a cookie
`curl -v -j -b tmp_cookie -L https://databus.dbpedia.org/imprint`

Simple curl doesn't work since the request redirects to keycloak, keycloak checks the session cookie for authentication information, fails since there is no cookie and redirects back to the first URL and enters a loop.

With a cookie the imprint page can redirect to keycloak, keycloak realizes that the user is not logged in, writes it to the cookie, redirects back and the imprint page can now see that it is not logged in and render "Not Logged In" to the HTML.

**Comment by JJ-Author** [comment]
can we close @kurzum

**Comment by kurzum** [comment]
ok
